{
  "modified": "2024-10-16T14:40:11Z",
  "published": "2024-10-16T14:40:11Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5105"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "eeeeeeeeeeeee344324f"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/eeeeeeeeeeeee344324f/MAL-2024-5105.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "651ff115ad199cf6bc442e75ba365d83b059e698c196f61f799501ffc2ce8d76",
        "import_time": "2024-10-24T00:59:09.960430394Z",
        "id": "RLUA-2024-08182",
        "modified_time": "2024-10-16T14:40:11Z"
      }
    ]
  }
}
