{
  "modified": "2024-06-25T13:32:50Z",
  "published": "2024-06-25T13:32:50Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "SNYK-PYTHON-BIPPUTILS-6513220"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "bipp-utils",
        "purl": "pkg:pypi/bipp-utils"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-BIPPUTILS-6513220"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "152b6a816d35a67ad15f7d159173ae0af8976ba3b29726f7474b9e0cb291d2ce",
        "import_time": "2024-06-28T02:48:22.013338433Z",
        "id": "RLMA-2024-03599",
        "modified_time": "2024-06-25T13:32:50Z",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
