{
  "modified": "2024-10-16T14:41:51Z",
  "published": "2024-10-16T14:41:51Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5196"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "hase"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/hase/MAL-2024-5196.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "8d2f1e893ea4b7d5998bf77ffb469496bbfdf9a969a8c757f857e1224f918963",
        "import_time": "2024-10-24T00:59:16.045946748Z",
        "id": "RLUA-2024-08338",
        "modified_time": "2024-10-16T14:41:51Z"
      }
    ]
  }
}
