{
  "modified": "2024-10-16T14:44:07Z",
  "published": "2024-10-16T14:44:07Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5401"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "networkdriver"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/networkdriver/MAL-2024-5401.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "63451540cd127740c2bc50e2952014aa2b23820fd4ca841a8078a7af593ceac0",
        "import_time": "2024-10-24T00:59:30.068157736Z",
        "id": "RLUA-2024-08557",
        "modified_time": "2024-10-16T14:44:07Z"
      }
    ]
  }
}
