{
  "modified": "2024-10-16T14:52:37Z",
  "published": "2024-10-16T14:52:37Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-6117"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "testingvvv3xx"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/testingvvv3xx/MAL-2024-6117.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "e6b2d9e3afdc8257be67b3e06e915fb566f2bf59ddf4b496484aa400ad751b5e",
        "import_time": "2024-10-24T01:00:18.97653566Z",
        "id": "RLUA-2024-09390",
        "modified_time": "2024-10-16T14:52:37Z"
      }
    ]
  }
}
