{
  "modified": "2024-10-16T14:37:34Z",
  "published": "2024-10-16T14:37:34Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-4864"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "capmonstercloudcliient"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/capmonstercloudcliient/MAL-2024-4864.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "b4072a129ff3719998dbeb7e6964c45f3de7254944a803909f47e14c74e831dd",
        "import_time": "2024-10-24T00:58:53.06595909Z",
        "id": "RLUA-2024-07932",
        "modified_time": "2024-10-16T14:37:34Z"
      }
    ]
  }
}
