{
  "modified": "2024-06-25T13:32:41Z",
  "published": "2024-06-25T13:32:41Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "SNYK-PYTHON-BIIPUTILS-6513730"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "biip-utils",
        "purl": "pkg:pypi/biip-utils"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-BIIPUTILS-6513730"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "14898e6db431033ee9aa53f7c7c5abccf476d6034d8aeb263026fc6186b24c3a",
        "import_time": "2024-06-28T02:48:19.961565599Z",
        "id": "RLMA-2024-03581",
        "modified_time": "2024-06-25T13:32:41Z",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
