{
  "modified": "2024-06-25T13:39:21Z",
  "published": "2024-06-25T13:39:21Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "SNYK-PYTHON-PYCYRD-6513660"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py-cyrd",
        "purl": "pkg:pypi/py-cyrd"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCYRD-6513660"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "b7002f54748f944969c41ac0be2a4481993b06ec0d8a2b4bb25e2be689a5c00a",
        "import_time": "2024-06-28T02:49:57.270609014Z",
        "id": "RLMA-2024-04412",
        "modified_time": "2024-06-25T13:39:21Z",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
