{
  "modified": "2024-06-25T13:40:34Z",
  "published": "2024-06-25T13:40:34Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "SNYK-PYTHON-PYPROTECTFILE-5295977"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pyprotectfile",
        "purl": "pkg:pypi/pyprotectfile"
      },
      "versions": [
        "1.0.1",
        "1.0.2",
        "1.0.3",
        "1.0.0"
      ]
    }
  ],
  "references": [
    {
      "type": "WEB",
      "url": "https://github.com/DataDog/malicious-software-packages-dataset"
    },
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYPROTECTFILE-5295977"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "a294bd0113cd55662b8b1169afe4e430d2626d2cdfbc6c091b3de6a19dabdcbf",
        "import_time": "2024-06-28T02:50:14.397744955Z",
        "id": "RLMA-2024-04558",
        "modified_time": "2024-06-25T13:40:34Z",
        "versions": [
          "1.0.1",
          "1.0.2",
          "1.0.3",
          "1.0.0"
        ]
      }
    ]
  }
}
